/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tables.tab1;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TAB1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(("{\"type\":\"record\",\"name\":\"TAB1\",\"namespace\":\"tables.acpdr\"," +
          "\"fields\":[{\"name\":\"table\",\"type\":\"string\"}," +
          "{\"name\":\"op_type\",\"type\":\"string\"}," +
          "{\"name\":\"op_ts\",\"type\":\"string\"}," +
          "{\"name\":\"current_ts\",\"type\":\"string\"}," +
          "{\"name\":\"pos\",\"type\":\"string\"}," +
          "{\"name\":\"primary_keys\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}," +
          "{\"name\":\"tokens\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"default\":{}}," +
          "{\"name\":\"before\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"columns\"," +
          "\"fields\":[{\"name\":\"CHPZXH\",\"type\":[\"null\",\"double\"]," +
          "\"default\":null},{\"name\":\"CHPZXH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CPZNXH\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"CPZNXH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CPXGBZ\",\"type\":[\"null\",\"string\"]," +
          "\"default\":null},{\"name\":\"CPXGBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"GUIYLS\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"GUIYLS_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"QANTRQ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"QANTRQ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"QTAILS\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"QTAILS_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YNJYRQ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YNJYRQ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YNGYLS\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YNGYLS_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIOYRQ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"JIOYRQ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHUJRQ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHUJRQ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIOYSJ\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"JIOYSJ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YNGYJG\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YNGYJG_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHNGJG\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHNGJG_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHNGDH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHNGDH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIAOYM\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"JIAOYM_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIO1GY\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"JIO1GY_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"SHOQGY\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"SHOQGY_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHYYJG\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHYYJG_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHKJJG\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHKJJG_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YEWUDH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YEWUDH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"HUOBDH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"HUOBDH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHAOXH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHAOXH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KMUHAO\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KMUHAO_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KEMUCC\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KEMUCC_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHANGH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHANGH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHUZZH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHUZZH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIEDBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"JIEDBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIO1JE\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"JIO1JE_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHHUYE\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"ZHHUYE_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YUEEFX\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YUEEFX_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"XNZHBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"XNZHBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KXHUBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KXHUBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"BCHZBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"BCHZBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CHBUBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"CHBUBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"GNGZQZ\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"GNGZQZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CUNQII\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"CUNQII_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"PNGZHH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"PNGZHH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KEHUZH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KEHUZH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KHZHLX\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KHZHLX_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"SHUNXH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"SHUNXH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHYODM\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHYODM_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHYOD2\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHYOD2_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"DFAKMH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"DFAKMH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"DUIFZH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"DUIFZH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"DUIFMC\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"DUIFMC_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"XJXMDM\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"XJXMDM_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KAHAOO\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KAHAOO_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"SHHUBH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"SHHUBH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"POSZBH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"POSZBH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"WAIWBH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"WAIWBH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"QUDAOO\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"QUDAOO_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"XITONG\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"XITONG_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YEWUBH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YEWUBH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"QIXIRQ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"QIXIRQ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"PAIJIA\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"PAIJIA_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"RJIEBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"RJIEBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"WAIHBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"WAIHBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"DXCZBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"DXCZBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"XIOZXH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"XIOZXH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"KEHHAO\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"KEHHAO_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"DJIBBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"DJIBBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"RZZHBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"RZZHBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"YUEEXZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"YUEEXZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"ZHUZWM\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"ZHUZWM_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JISHUU\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"JISHUU_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JIEJUH\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"JIEJUH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"DAYNBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"DAYNBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"PZJCBZ\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"PZJCBZ_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CPBH01\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"CPBH01_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CPBH02\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"CPBH02_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"CPBH03\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"CPBH03_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"BEIY01\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"BEIY01_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"BEIY04\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"BEIY04_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"BEIY40\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"BEIY40_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"BEYINT\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"BEYINT_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"BEYDEC\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"BEYDEC_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"SHJNCH\",\"type\":[\"null\",\"double\"],\"default\":null}," +
          "{\"name\":\"SHJNCH_isMissing\",\"type\":\"boolean\"}," +
          "{\"name\":\"JILUZT\",\"type\":[\"null\",\"string\"],\"default\":null}," +
          "{\"name\":\"JILUZT_isMissing\",\"type\":\"boolean\"}]}],\"default\":null}," +
          "{\"name\":\"after\",\"type\":[\"null\",\"columns\"],\"default\":null}]}"));
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public CharSequence table;
  @Deprecated public CharSequence op_type;
  @Deprecated public CharSequence op_ts;
  @Deprecated public CharSequence current_ts;
  @Deprecated public CharSequence pos;
  @Deprecated public java.util.List<CharSequence> primary_keys;
  @Deprecated public java.util.Map<CharSequence,CharSequence> tokens;
  @Deprecated public tables.tab1.columns before;
  @Deprecated public tables.tab1.columns after;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TAB1() {}

  /**
   * All-args constructor.
   */
  public TAB1(CharSequence table, CharSequence op_type, CharSequence op_ts, CharSequence current_ts, CharSequence pos, java.util.List<CharSequence> primary_keys, java.util.Map<CharSequence,CharSequence> tokens, tables.tab1.columns before, tables.tab1.columns after) {
    this.table = table;
    this.op_type = op_type;
    this.op_ts = op_ts;
    this.current_ts = current_ts;
    this.pos = pos;
    this.primary_keys = primary_keys;
    this.tokens = tokens;
    this.before = before;
    this.after = after;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return table;
    case 1: return op_type;
    case 2: return op_ts;
    case 3: return current_ts;
    case 4: return pos;
    case 5: return primary_keys;
    case 6: return tokens;
    case 7: return before;
    case 8: return after;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: table = (CharSequence)value$; break;
    case 1: op_type = (CharSequence)value$; break;
    case 2: op_ts = (CharSequence)value$; break;
    case 3: current_ts = (CharSequence)value$; break;
    case 4: pos = (CharSequence)value$; break;
    case 5: primary_keys = (java.util.List<CharSequence>)value$; break;
    case 6: tokens = (java.util.Map<CharSequence,CharSequence>)value$; break;
    case 7: before = (tables.tab1.columns)value$; break;
    case 8: after = (tables.tab1.columns)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'table' field.
   */
  public CharSequence getTable() {
    return table;
  }

  /**
   * Sets the value of the 'table' field.
   * @param value the value to set.
   */
  public void setTable(CharSequence value) {
    this.table = value;
  }

  /**
   * Gets the value of the 'op_type' field.
   */
  public CharSequence getOpType() {
    return op_type;
  }

  /**
   * Sets the value of the 'op_type' field.
   * @param value the value to set.
   */
  public void setOpType(CharSequence value) {
    this.op_type = value;
  }

  /**
   * Gets the value of the 'op_ts' field.
   */
  public CharSequence getOpTs() {
    return op_ts;
  }

  /**
   * Sets the value of the 'op_ts' field.
   * @param value the value to set.
   */
  public void setOpTs(CharSequence value) {
    this.op_ts = value;
  }

  /**
   * Gets the value of the 'current_ts' field.
   */
  public CharSequence getCurrentTs() {
    return current_ts;
  }

  /**
   * Sets the value of the 'current_ts' field.
   * @param value the value to set.
   */
  public void setCurrentTs(CharSequence value) {
    this.current_ts = value;
  }

  /**
   * Gets the value of the 'pos' field.
   */
  public CharSequence getPos() {
    return pos;
  }

  /**
   * Sets the value of the 'pos' field.
   * @param value the value to set.
   */
  public void setPos(CharSequence value) {
    this.pos = value;
  }

  /**
   * Gets the value of the 'primary_keys' field.
   */
  public java.util.List<CharSequence> getPrimaryKeys() {
    return primary_keys;
  }

  /**
   * Sets the value of the 'primary_keys' field.
   * @param value the value to set.
   */
  public void setPrimaryKeys(java.util.List<CharSequence> value) {
    this.primary_keys = value;
  }

  /**
   * Gets the value of the 'tokens' field.
   */
  public java.util.Map<CharSequence,CharSequence> getTokens() {
    return tokens;
  }

  /**
   * Sets the value of the 'tokens' field.
   * @param value the value to set.
   */
  public void setTokens(java.util.Map<CharSequence,CharSequence> value) {
    this.tokens = value;
  }

  /**
   * Gets the value of the 'before' field.
   */
  public tables.tab1.columns getBefore() {
    return before;
  }

  /**
   * Sets the value of the 'before' field.
   * @param value the value to set.
   */
  public void setBefore(tables.tab1.columns value) {
    this.before = value;
  }

  /**
   * Gets the value of the 'after' field.
   */
  public tables.tab1.columns getAfter() {
    return after;
  }

  /**
   * Sets the value of the 'after' field.
   * @param value the value to set.
   */
  public void setAfter(tables.tab1.columns value) {
    this.after = value;
  }

  /** Creates a new TAB1 RecordBuilder */
  public static TAB1.Builder newBuilder() {
    return new TAB1.Builder();
  }
  
  /** Creates a new TAB1 RecordBuilder by copying an existing Builder */
  public static TAB1.Builder newBuilder(TAB1.Builder other) {
    return new TAB1.Builder(other);
  }
  
  /** Creates a new TAB1 RecordBuilder by copying an existing TAB1 instance */
  public static TAB1.Builder newBuilder(TAB1 other) {
    return new TAB1.Builder(other);
  }
  
  /**
   * RecordBuilder for TAB1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TAB1>
    implements org.apache.avro.data.RecordBuilder<TAB1> {

    private CharSequence table;
    private CharSequence op_type;
    private CharSequence op_ts;
    private CharSequence current_ts;
    private CharSequence pos;
    private java.util.List<CharSequence> primary_keys;
    private java.util.Map<CharSequence,CharSequence> tokens;
    private tables.tab1.columns before;
    private tables.tab1.columns after;

    /** Creates a new Builder */
    private Builder() {
      super(TAB1.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(TAB1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.table)) {
        this.table = data().deepCopy(fields()[0].schema(), other.table);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.op_type)) {
        this.op_type = data().deepCopy(fields()[1].schema(), other.op_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.op_ts)) {
        this.op_ts = data().deepCopy(fields()[2].schema(), other.op_ts);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.current_ts)) {
        this.current_ts = data().deepCopy(fields()[3].schema(), other.current_ts);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pos)) {
        this.pos = data().deepCopy(fields()[4].schema(), other.pos);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.primary_keys)) {
        this.primary_keys = data().deepCopy(fields()[5].schema(), other.primary_keys);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tokens)) {
        this.tokens = data().deepCopy(fields()[6].schema(), other.tokens);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.before)) {
        this.before = data().deepCopy(fields()[7].schema(), other.before);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.after)) {
        this.after = data().deepCopy(fields()[8].schema(), other.after);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TAB1 instance */
    private Builder(TAB1 other) {
            super(TAB1.SCHEMA$);
      if (isValidValue(fields()[0], other.table)) {
        this.table = data().deepCopy(fields()[0].schema(), other.table);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.op_type)) {
        this.op_type = data().deepCopy(fields()[1].schema(), other.op_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.op_ts)) {
        this.op_ts = data().deepCopy(fields()[2].schema(), other.op_ts);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.current_ts)) {
        this.current_ts = data().deepCopy(fields()[3].schema(), other.current_ts);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pos)) {
        this.pos = data().deepCopy(fields()[4].schema(), other.pos);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.primary_keys)) {
        this.primary_keys = data().deepCopy(fields()[5].schema(), other.primary_keys);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tokens)) {
        this.tokens = data().deepCopy(fields()[6].schema(), other.tokens);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.before)) {
        this.before = data().deepCopy(fields()[7].schema(), other.before);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.after)) {
        this.after = data().deepCopy(fields()[8].schema(), other.after);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'table' field */
    public CharSequence getTable() {
      return table;
    }
    
    /** Sets the value of the 'table' field */
    public TAB1.Builder setTable(CharSequence value) {
      validate(fields()[0], value);
      this.table = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'table' field has been set */
    public boolean hasTable() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'table' field */
    public TAB1.Builder clearTable() {
      table = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'op_type' field */
    public CharSequence getOpType() {
      return op_type;
    }
    
    /** Sets the value of the 'op_type' field */
    public TAB1.Builder setOpType(CharSequence value) {
      validate(fields()[1], value);
      this.op_type = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'op_type' field has been set */
    public boolean hasOpType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'op_type' field */
    public TAB1.Builder clearOpType() {
      op_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'op_ts' field */
    public CharSequence getOpTs() {
      return op_ts;
    }
    
    /** Sets the value of the 'op_ts' field */
    public TAB1.Builder setOpTs(CharSequence value) {
      validate(fields()[2], value);
      this.op_ts = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'op_ts' field has been set */
    public boolean hasOpTs() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'op_ts' field */
    public TAB1.Builder clearOpTs() {
      op_ts = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'current_ts' field */
    public CharSequence getCurrentTs() {
      return current_ts;
    }
    
    /** Sets the value of the 'current_ts' field */
    public TAB1.Builder setCurrentTs(CharSequence value) {
      validate(fields()[3], value);
      this.current_ts = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'current_ts' field has been set */
    public boolean hasCurrentTs() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'current_ts' field */
    public TAB1.Builder clearCurrentTs() {
      current_ts = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'pos' field */
    public CharSequence getPos() {
      return pos;
    }
    
    /** Sets the value of the 'pos' field */
    public TAB1.Builder setPos(CharSequence value) {
      validate(fields()[4], value);
      this.pos = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'pos' field has been set */
    public boolean hasPos() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'pos' field */
    public TAB1.Builder clearPos() {
      pos = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'primary_keys' field */
    public java.util.List<CharSequence> getPrimaryKeys() {
      return primary_keys;
    }
    
    /** Sets the value of the 'primary_keys' field */
    public TAB1.Builder setPrimaryKeys(java.util.List<CharSequence> value) {
      validate(fields()[5], value);
      this.primary_keys = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'primary_keys' field has been set */
    public boolean hasPrimaryKeys() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'primary_keys' field */
    public TAB1.Builder clearPrimaryKeys() {
      primary_keys = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'tokens' field */
    public java.util.Map<CharSequence,CharSequence> getTokens() {
      return tokens;
    }
    
    /** Sets the value of the 'tokens' field */
    public TAB1.Builder setTokens(java.util.Map<CharSequence,CharSequence> value) {
      validate(fields()[6], value);
      this.tokens = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'tokens' field has been set */
    public boolean hasTokens() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'tokens' field */
    public TAB1.Builder clearTokens() {
      tokens = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'before' field */
    public tables.tab1.columns getBefore() {
      return before;
    }
    
    /** Sets the value of the 'before' field */
    public TAB1.Builder setBefore(tables.tab1.columns value) {
      validate(fields()[7], value);
      this.before = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'before' field has been set */
    public boolean hasBefore() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'before' field */
    public TAB1.Builder clearBefore() {
      before = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'after' field */
    public tables.tab1.columns getAfter() {
      return after;
    }
    
    /** Sets the value of the 'after' field */
    public TAB1.Builder setAfter(tables.tab1.columns value) {
      validate(fields()[8], value);
      this.after = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'after' field has been set */
    public boolean hasAfter() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'after' field */
    public TAB1.Builder clearAfter() {
      after = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public TAB1 build() {
      try {
        TAB1 record = new TAB1();
        record.table = fieldSetFlags()[0] ? this.table : (CharSequence) defaultValue(fields()[0]);
        record.op_type = fieldSetFlags()[1] ? this.op_type : (CharSequence) defaultValue(fields()[1]);
        record.op_ts = fieldSetFlags()[2] ? this.op_ts : (CharSequence) defaultValue(fields()[2]);
        record.current_ts = fieldSetFlags()[3] ? this.current_ts : (CharSequence) defaultValue(fields()[3]);
        record.pos = fieldSetFlags()[4] ? this.pos : (CharSequence) defaultValue(fields()[4]);
        record.primary_keys = fieldSetFlags()[5] ? this.primary_keys : (java.util.List<CharSequence>) defaultValue(fields()[5]);
        record.tokens = fieldSetFlags()[6] ? this.tokens : (java.util.Map<CharSequence,CharSequence>) defaultValue(fields()[6]);
        record.before = fieldSetFlags()[7] ? this.before : (tables.tab1.columns) defaultValue(fields()[7]);
        record.after = fieldSetFlags()[8] ? this.after : (tables.tab1.columns) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
